import { test, expect } from '@playwright/test';

test.describe('Massive Data Rendering & Responsiveness', () => {
  // Use admin auth state generated by global-setup
  test.use({ storageState: 'tests/.auth/admin.json' });

  test('should render players list with massive data correctly', async ({ page }) => {
    // Navigating to players/roster page
    await page.goto('http://localhost:5173/roster');
    
    // Check if the list renders.
    // Wait for the grid buttons to be visible
    await page.waitForSelector('button.text-left.bg-white.rounded-xl', { state: 'visible', timeout: 10000 });
    
    // Assert that we have multiple rows rendered (pagination is handled)
    const items = await page.locator('button.text-left.bg-white.rounded-xl').count();
    expect(items).toBeGreaterThan(0);
    expect(items).toBeLessThanOrEqual(24); // Based on PAGE_SIZE = 24
    
    // Check responsiveness by resizing to mobile
    await page.setViewportSize({ width: 375, height: 812 });
    const bodyWidth = await page.evaluate(() => document.body.scrollWidth);
    const windowWidth = await page.evaluate(() => window.innerWidth);
    expect(bodyWidth).toBeLessThanOrEqual(windowWidth + 10); // allow slight margin
  });

  test('should render events list and handle transitions smoothly', async ({ page }) => {
    await page.goto('http://localhost:5173/eventos');
    
    // Wait for events to load - they are divs with bg-white border rounded-lg
    await page.waitForSelector('div.bg-white.border.rounded-lg.p-4', { state: 'visible', timeout: 30000 });
    
    // Check elements
    const eventItems = await page.locator('div.bg-white.border.rounded-lg.p-4').count();
    expect(eventItems).toBeGreaterThan(0);
  });
});
